language: node_js
node_js:
  "11.10.1"
cache:
  directories:
    "node_modules"
script:
  npm run test:unit
  npm run build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist
  github_token: $GITHUB_TOKEN
  on:
    branch: master